genpulse:
    base_path: models/ComfyUI_models
    checkpoints: checkpoints/
    clip: clip/
    clip_vision: clip_vision/
    configs: configs/
    controlnet: controlnet/
    diffusion_models: diffusion_models/
    embeddings: embeddings/
    gligen: gligen/
    hypernetworks: hypernetworks/
    loras: loras/
    style_models: style_models/
    unet: unet/
    upscale_models: upscale_models/
    vae: vae/
    vae_approx: vae_approx/
